# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

# Add a step to install dependencies using pip
- script: |
    python -m pip install -r requirements.txt
  displayName: 'Install Dependencies'

# Add a step to run your tests here
- script: |
    python -m unittest discover tests
  displayName: 'Run Unit Tests'